# -*- coding: utf-8 -*-

COMPREHENSIVE = 0
CRITICAL_DISEASE = 1
EDUCATION = 2

# 意愿种类
NOPACKAGE = 0
BALANCE = 1
MEDICAL_WITH_SOCIAL_INSURANCE = 2
MEDICAL = 3
DISEASE = 4
ACCIDENT = 5

RECOMMEND = 1
BACKUP = 2

PACKAGE_NO = 0
PACKAGE_BASIC = 1
PACKAGE_MEDICAL = 2
PACKAGE_DISEASE = 3
PACKAGE_ACCIDENT = 4
PACKAGE_UPGRADE_1 = 5
PACKAGE_UPGRADE_2 = 6

INS_SUB_TITLE_NUMBER_10 = '10'
INS_SUB_TITLE_NUMBER_20 = '20'

MALE = 'M'
FEMALE = 'F'

HAS_SOCIAL_INSURANCE = '1'
HAS_SUPPLEMENT = '1'
