# coding: utf-8

from decimal import Decimal


NEW_COMER_PRODUCT_GIFT_PERIOD_VALUE = 7
NEW_COMER_PRODUCT_EFFECTIVE_AMOUNT_LIMIT = Decimal('10000.00')
NEW_COMER_PRODUCT_OPERATION_NUM = Decimal('0.15')
